### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by krathalan** [tastytea/hashboot#18]
Hello, I'm sure you've noticed I've made a few PRs for Arch instructions. I'm interested in becoming the maintainer for a hashboot package on the Arch User Repository, and pretty much everything works so far. I'll need two things from you, however.

~~First, you'll have to convert the `hashboot.1.adoc` asciidoc file to a man page with the command `a2x -f manpage hashboot.1.adoc`. It will output the file `hashboot.1` in the root of the repository. This is a proper manpage and works correctly when installed.~~ I found the `build_manpage.sh` file, added the proper make dependecy (the `asciidoc` package), and made the PKGBUILD run `build_manpage.sh` before installing. You no longer need to add this to the repository.

Secondly, you'll have to include a pacman hook file; the PKGBUILD I've written assumes it will be named `99-hashboot.hook` in the root of the repository.

The pacman hook file should contain the following content, as per the Arch instructions I've already submitted:

```
[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = Package
Target = *

[Action]
Description = Regenerating hashboot checksums...
When = PostTransaction
Exec = /usr/bin/hashboot index
Depends = hashboot
```

You can look at the two files necessary (a `PKGBUILD` and `hashboot.install` file) I've written here: https://gitlab.com/krathalan/hashboot-aur

If you wish to change the location of any files, please let me know and I will update accordingly. I'd like to cooperate with you and make any changes to the package that you request -- or if you'd rather me not publish a package, I'm okay with that too. However, I would very much like to and would be committed to publishing further updates and working with you to resolve issues when necessary. 

Edit: Update hook with "Depends" line

**Comment by krathalan** [comment]
I forgot to mention that Arch recommends that the sha256sums be provided by upstream as well -- I've calculated my own sha256sum, but it would be nice to have one published by you.

**Comment by krathalan** [comment]
Additionally, if you publish a signature file for the release as a .sig or .asc file and publish the relevant key on a keyserver, the PKGBUILD can be configured to verify the download with GPG as well.

**Comment by tastytea** [comment]
I've added the hook to `hooks/pacman.hook`. Once I found a good way to add checksums and signatures automatically, I will make a new release.

**Comment by tastytea** [comment]
The repo moved to <https://schlomp.space/tastytea/hashboot>. Each new release has now checksums and PGP-signatures. Apart from the URL, you will need to change `cd "$srcdir/${pkgname}-${pkgver}"` to `cd "$srcdir/${pkgname}"` in `prepare()`, because Gitea doesn't put the version in the folder name.

**Comment by krathalan** [comment]
Awesome, thanks! I've updated the `hashboot-aur` repo accordingly. 

Without editing the user's `~/.gnupg/gpg.conf`, the GPG key can't be received automatically, but `makepkg` will print an error saying the user needs to have the key "242E5AC4DA587BF9". After running `gpg --recv-keys 242E5AC4DA587BF9`, `makepkg` automatically verifies the GPG signature (and the sha512sums). 

Edit: I forgot the most popular AUR helper (`yay`) handles this with a prompt automatically.

Are there any other edits/corrections/etc?

**Comment by krathalan** [comment]
I've published it to the AUR! https://aur.archlinux.org/packages/hashboot/

I'd recommend deleting the prior Arch instructions I submitted, as (1) it's better to let pacman keep track of files than the user, and (2) I was having issues with linking the hashboot files and systemd anyways.

**Comment by tastytea** [comment]
Thanks! It seems there are several ways of installing packages from AUR. Which should I recommend in the readme?

**Comment by krathalan** [comment]
Many developers don't recommend a specific way, but rather just say that the package is on the AUR (with a link) and don't give full instructions. My preferred way is with `yay` (https://aur.archlinux.org/packages/yay/), since it makes installing AUR packages as easy as regular packages, but many people prefer to do it manually or with a different AUR tool.

**Comment by krathalan** [comment]
I deleted the original `hashboot-aur` repository on GitLab. The GitLab repository is now at https://gitlab.com/krathalan/hashboot and is simply a mirror of the AUR repository at https://aur.archlinux.org/cgit/aur.git/tree/?h=hashboot.

**Comment by tastytea** [comment]
I've updated the readme. Thanks again!

**Comment by krathalan** [comment]
Thanks! :)
