### ISSUE TITLE
No clear explanation of differences between this and other checksumming solutions

### ISSUE THREAD

**Issue by CameronNemo** [tastytea/hashboot#4]
See for example [dm-integrity](https://lwn.net/Articles/533558/).

**Comment by tastytea** [comment]
Thanks for your report.

hashboot hashes all files in `/boot` to check them during early boot. It is intended for when you have encrypted the root partition but not the boot partition. The checksums and a backup of the contents of `/boot` are stored outside `/boot`. If a checksum doesn't match, you have the option to restore the file from backup.

I'll add a description to the README shortly.
